// https://twitter.com/sulaimanghori - Kek or cringe?

export const loading_messages = [
    "Because typing is hard.",
    "Converting speech, because speaking is easier than typing.",
    "Converting speech, unlocking the power of the spoken word.",
    "Convincing the word wizard...",
    "Decoding your words of wisdom...",
    "Herding cats...",
    "Hold on tight, text incoming soon.",
    "Hold on tight, your text is on its way.",
    "Hold on tight, your words are about to turn into text.",
    "Hold on tight, your words are being transformed into text.",
    "Hold your horses, your text is on its way.",
    "Loading... because typing is overrated.",
    "Not doing brain surgery...",
    "Patience is a virtue.",
    "Playing Jenga...",
    "Playing Tetris...",
    "Playing whack-a-mole.",
    "Please wait while we transcribe your brilliance.",
    "Speak now, text later.",
    "Speech into text, easy peasy.",
    "Speech-to-text, because typing is hard.",
    "Speech-to-text, because we're also too lazy to type.",
    "Speech-to-text, capturing your voice, your way.",
    "Speech-to-text, faster than typing.",
    "Speech-to-text, no manual labor required.",
    "Speech-to-text, the lazy person's guide to typing.",
    "Speech-to-text, the smart way to not type.",
    "Speech-to-text, turning your voice into written gold.",
    "Speech-to-text, your words transmogrified into text.",
    "Transcribing speech, no sweat (almost).",
    "Transcribing your speech, because typing is so last year.",
    "Transcribing your speech, because we believe words matter.",
    "Transcribing your speech, one syllable at a time.",
    "Transcribing your speech, one word at a time.",
    "Transcribing your speech, so you don't have to.",
    "Transcribing your speech, with love and care.",
    "Transcribing your speech, with more accuracy than your spell-checker.",
    "Transcribing your words like a pro.",
    "Transcribing, because typing is for amateurs.",
    "Transcribing, capturing your words with surgical precision.",
    "Transcribing, decoding the language of humans.",
    "Transcribing, decoding the mysteries of speech.",
    "Transcribing, making words great again.",
    "Transcribing, turning your speech into text with love.",
    "Transcribing, turning your voice into digital ink.",
    "Transcribing, turning your voice into wordsmithery.",
    "Trying to find Waldo...",
    "Untangling headphones...",
    "Words in progress.",
    "Words to text, bringing your words to life.",
    "Words to text, capturing the essence of your voice.",
]
