name: Build Obsidian Transcription Beta
# Thanks @ClareMacrae!

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            # Cache dependencies
            - name: Cache pnpm modules
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            # Install pnpm
            - name: Install pnpm
              run: npm install -g pnpm

            # Install modules using pnpm
            - name: Install modules
              run: pnpm install

            # Rest of your steps
            - name: Run build
              run: pnpm run build

            - name: Run TypeScript compiler ESLint
              run: pnpm run lint

            - name: Archive verified build
              uses: actions/upload-artifact@v4
              with:
                  name: obsidian-transcription
                  path: |
                      main.js
                      manifest.json
                      styles.css

            # https://github.com/obsidian-tasks-group/obsidian-tasks/blob/7585a058e4c3f1a220a4ba8079f6897d92e52dbe/.github/workflows/verify.yml#L29-L46
            # - name: Copy new build to Tasks-Demo vault
            #   run: ./scripts/Test-TasksInLocalObsidian.sh

            # - name: Archive Tasks-Demo vault
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: Tasks-Demo-VerifyCommit-Build${{ github.run_number }}-Run${{ github.run_attempt }}
            #     path: |
            #       resources/sample_vaults/Tasks-Demo
